### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by massger** [shfc/JincinExamHelper#2]
不知道是不是因为锦成网升级了，这个脚本在答题过程中的自动填写答案功能失效，可以交流一下是什么问题

**Comment by Qinet** [comment]
抱歉，目前已不在学校，也没有测试帐号了，所以已经不再维护了，初步判断应该是填写答案的[JS脚本](https://github.com/Qinet/JincinExamHelper/blob/89155ad263728b8a309e782bd67ef9f966317581/conf.cfg#L3)失效了。

**Comment by toolor** [comment]
请问你能更新一下软件吗？

**Comment by Qinet** [comment]
@toolor 暂时停止维护，抱歉。目前仅自动填写答案功能失效，可选择手动答题。

**Comment by nengbowan** [comment]
ERROR:root:Load online bank fail;Error:
DEBUG:root:Load local bank...
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): github.com
Traceback (most recent call last):
  File "main.py", line 217, in <module>
    frame = MainFrame(None, u"%s" % __title__)
  File "main.py", line 144, in __init__
    self.splitter.SetMinimumPaneSize(min=100)
TypeError: SplitterWindow.SetMinimumPaneSize(): 'min' is not a valid keyword argument
DEBUG:requests.packages.urllib3.connectionpool:"GET /Qinet/JincinExamHelper/raw/master/online_question_bank HTTP/1.1" 302 150
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): raw.githubusercontent.com
DEBUG:requests.packages.urllib3.connectionpool:"GET /Qinet/JincinExamHelper/master/online_question_bank HTTP/1.1" 200 211817
DEBUG:root:Load online bank success!
ERROR:root:Load online bank fail;Error:
DEBUG:root:Load local bank...
DEBUG:root:use online question bank instead of local bank!
